Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2031, in try_parse
    return packaging.version.Version(name)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'py3.10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jblevins32/ros2_ws/py_pubsub/setup.py", line 1, in <module>
    from setuptools import find_packages, setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3302, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 613, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2073, in find_on_path
    path_item_entries = _by_version_descending(filtered)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2043, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2041, in _by_version
    return [try_parse(part) for part in parts]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2041, in <listcomp>
    return [try_parse(part) for part in parts]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2033, in try_parse
    return packaging.version.Version('0')
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 271, in __init__
    release=tuple(int(i) for i in match.group("release").split(".")),
KeyboardInterrupt
